[package]
name = "qobuz-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "qobuz"
path = "src/main.rs"

[dependencies]

qobuz = { path = "../" }

url = { workspace = true }
tokio = { workspace = true }

clap = { version = "4.5.30", features = ["derive"] }
